# Generated by Django 4.2 on 2024-05-01 10:54

from django.db import migrations, models
import operation.helpers.model.base
import utils.helpers.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='full name')),
                ('url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='repo url')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='extra_info')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=operation.helpers.model.base.partner_image_location)),
            ],
            bases=(utils.helpers.models.base.BaseModelBaseMixin, utils.helpers.models.base.CloudinaryDeleteMixin, models.Model),
        ),
    ]
