# Generated by Django 5.1.14 on 2026-04-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_rename_checkin_status_checkin_time_idx_checkin_status_time_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubregistration',
            name='phone_number',
            field=models.CharField(help_text='International formats; length only in the API.', max_length=64, verbose_name='phone number'),
        ),
    ]
