# Generated by Django 4.2 on 2024-05-06 20:16

from django.db import migrations, models
import utils.helpers.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=utils.helpers.models.base.image_location)),
            ],
        ),
    ]
