# Generated by Django 5.1.7 on 2025-05-15 07:46

import cloudinary_storage.storage
import utils.helpers.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_image_created_at_image_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=utils.helpers.models.base.image_location),
        ),
    ]
