# Generated by Django 4.2 on 2024-04-12 12:16

import cohort.helpers.model.base
from django.db import migrations, models
import django.db.models.deletion
import utils.helpers.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='course name')),
                ('description', models.TextField(verbose_name='description')),
                ('venue', models.JSONField(default=list, verbose_name='venue')),
                ('extra_info', models.TextField(verbose_name='extra_info')),
                ('status', models.BooleanField(default=True)),
                ('images', models.ManyToManyField(related_name='related_images', to='utils.image')),
            ],
            bases=(utils.helpers.models.base.BaseModelBaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=1000, verbose_name='headline')),
                ('full_name', models.CharField(max_length=255, verbose_name='last name')),
                ('testimony', models.TextField(verbose_name='testimony')),
                ('picture', models.ImageField(upload_to=cohort.helpers.model.base.testimonial_image_location)),
                ('brief', models.CharField(max_length=255, verbose_name='author brief')),
            ],
            bases=(utils.helpers.models.base.BaseModelBaseMixin, utils.helpers.models.base.CloudinaryDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='registration name')),
                ('is_open', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohort.course')),
            ],
            bases=(utils.helpers.models.base.BaseModelBaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('wallet_address', models.CharField(max_length=255, verbose_name='first name')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('about', models.TextField(verbose_name='about')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohort.registration')),
            ],
            bases=(utils.helpers.models.base.BaseModelBaseMixin, models.Model),
        ),
    ]
