# Generated by Django 4.2 on 2024-03-24 04:32

import apps.utils.helpers.models.base
import cohort.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(apps.utils.helpers.models.base.BaseModelBaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(apps.utils.helpers.models.base.BaseModelBaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=1000, verbose_name='headline')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('testimony', models.TextField(verbose_name='testimony')),
                ('picture', models.ImageField(upload_to=cohort.models.testimonial_image_location)),
                ('brief', models.CharField(max_length=255, verbose_name='author brief')),
            ],
            bases=(apps.utils.helpers.models.base.BaseModelBaseMixin, models.Model),
        ),
    ]
