# Generated by Django 4.2 on 2024-05-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='about',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_name',
        ),
        migrations.AddField(
            model_name='participant',
            name='achievement',
            field=models.TextField(blank=True, null=True, verbose_name='achievement'),
        ),
        migrations.AddField(
            model_name='participant',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='city name'),
        ),
        migrations.AddField(
            model_name='participant',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='country name'),
        ),
        migrations.AddField(
            model_name='participant',
            name='duration',
            field=models.CharField(max_length=100, null=True, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(max_length=20, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='participant',
            name='github',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='github url'),
        ),
        migrations.AddField(
            model_name='participant',
            name='motivation',
            field=models.TextField(null=True, verbose_name='motivation'),
        ),
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='participant',
            name='number',
            field=models.CharField(max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.CharField(max_length=255, verbose_name='participant email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='wallet_address',
            field=models.CharField(max_length=255, verbose_name='wallet address'),
        ),
    ]
