# Generated by Django 5.1.4 on 2025-01-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0002_remove_participant_duration_course_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='participant email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='github',
            field=models.URLField(blank=True, default='', max_length=250, verbose_name='github url'),
        ),
    ]
