# Generated by Django 4.2 on 2024-05-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0002_remove_participant_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registrationFee',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='registration fee'),
        ),
    ]
