# Generated by Django 4.2 on 2024-05-06 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0003_registration_registrationfee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('email', 'registration')},
        ),
    ]
