# Generated by Django 5.1.4 on 2025-01-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0003_alter_participant_email_alter_participant_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='3 months', max_length=100, verbose_name='duration'),
        ),
    ]
