# Generated by Django 5.1.4 on 2025-01-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0004_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
