# Generated by Django 4.2 on 2024-05-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0004_alter_participant_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='course',
        ),
        migrations.AddField(
            model_name='participant',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cohort.course'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
