# Generated by Django 5.1.4 on 2025-01-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0005_participant_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cohort',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='cohort name'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('email', 'registration')},
        ),
    ]
