# Generated by Django 5.1.4 on 2025-01-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0006_registration_cohort_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='picture',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='picture_link',
            field=models.URLField(blank=True, default='', max_length=250, verbose_name='picture link'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='headline',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='headline'),
        ),
    ]
