# Generated by Django 5.1.4 on 2025-02-01 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0007_remove_testimonial_brief_remove_testimonial_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='cohort.registration'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cohort.course'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cohort.registration'),
        ),
    ]
