# Generated by Django 5.1.7 on 2025-03-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0008_alter_course_registration_alter_participant_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='achievement',
            field=models.TextField(null=True, verbose_name='achievement'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='cohort',
            field=models.CharField(default='Cohort-XIII', max_length=20, verbose_name='cohort name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='cohort',
            field=models.CharField(default='Cohort-XIII', max_length=20, verbose_name='cohort name'),
        ),
    ]
