# Generated by Django 5.1.7 on 2025-03-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0009_alter_participant_achievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='full name'),
        ),
    ]
