# Generated by Django 5.1.7 on 2025-05-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0010_alter_participant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='venue',
            field=models.CharField(default='online', max_length=30, verbose_name='venue'),
        ),
    ]
