# Generated by Django 5.1.14 on 2026-04-21 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0020_alter_participant_number_max_length_64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='cohort',
            field=models.CharField(blank=True, help_text='Set from the course’s programme on enroll; may be null for legacy rows.', max_length=20, null=True, verbose_name='cohort name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registration',
            field=models.ForeignKey(help_text='Programme (Registration) for payments and reporting; copied from Course.registration on save when missing.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cohort.registration'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='cohort',
            field=models.CharField(blank=True, help_text='Optional label (e.g. Web3, Web2). Set on each programme in admin.', max_length=20, null=True, verbose_name='cohort name'),
        ),
    ]
