# Generated by Django 5.0.1 on 2024-11-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('email', models.EmailField(max_length=127, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.BooleanField()),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('transaction_ref', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('claimant', models.EmailField(blank=True, max_length=127)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
