# Generated by Django 5.1.4 on 2025-01-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
