# Generated by Django 5.1.6 on 2025-06-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_discountcode_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, null=True),
        ),
    ]
