from fastapi import APIRouter, Depends, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_mentor_user
from app.db.session import get_db_session
from app.models.portal import User
from app.schemas.attendance import (
    AttendanceCodeDetailResponse,
    AttendanceCodeResponse,
    CreateAttendanceCodeRequest,
    StudentAttendanceSubmitRequest,
    StudentAttendanceSubmitResponse,
)
from app.schemas.auth import MessageResponse
from app.services.attendance import AttendanceService

router = APIRouter(tags=["Attendance Management"])


@router.post(
    "/mentor/attendance/codes",
    response_model=AttendanceCodeResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate attendance code",
    description="Allows mentors to generate a unique attendance code for a class.",
)
async def create_attendance_code(
    payload: CreateAttendanceCodeRequest,
    current_user: User = Depends(get_current_mentor_user),
    db: AsyncSession = Depends(get_db_session),
) -> AttendanceCodeResponse:
    return await AttendanceService(db).create_attendance_code(actor=current_user, payload=payload)


@router.get(
    "/mentor/attendance/codes",
    response_model=list[AttendanceCodeResponse],
    status_code=status.HTTP_200_OK,
    summary="List generated attendance codes",
    description="Returns all attendance codes generated by the authenticated mentor.",
)
async def list_attendance_codes(
    current_user: User = Depends(get_current_mentor_user),
    db: AsyncSession = Depends(get_db_session),
) -> list[AttendanceCodeResponse]:
    return await AttendanceService(db).list_mentor_attendance_codes(actor=current_user)


@router.get(
    "/mentor/attendance/codes/{code_id}",
    response_model=AttendanceCodeDetailResponse,
    status_code=status.HTTP_200_OK,
    summary="Get attendance code details and attendees",
    description="Returns details for an attendance code along with the list of students who signed.",
)
async def get_attendance_code_details(
    code_id: int,
    current_user: User = Depends(get_current_mentor_user),
    db: AsyncSession = Depends(get_db_session),
) -> AttendanceCodeDetailResponse:
    return await AttendanceService(db).get_attendance_code_details(
        actor=current_user, code_id=code_id
    )


@router.patch(
    "/mentor/attendance/codes/{code_id}/deactivate",
    response_model=AttendanceCodeResponse,
    status_code=status.HTTP_200_OK,
    summary="Deactivate attendance code",
    description="Immediately sets isActive = false for the specified attendance code.",
)
async def deactivate_attendance_code(
    code_id: int,
    current_user: User = Depends(get_current_mentor_user),
    db: AsyncSession = Depends(get_db_session),
) -> AttendanceCodeResponse:
    return await AttendanceService(db).deactivate_attendance_code(
        actor=current_user, code_id=code_id
    )


@router.delete(
    "/mentor/attendance/codes/{code_id}",
    response_model=MessageResponse,
    status_code=status.HTTP_200_OK,
    summary="Delete attendance code",
    description="Deletes an attendance code generated by the mentor.",
)
async def delete_attendance_code(
    code_id: int,
    current_user: User = Depends(get_current_mentor_user),
    db: AsyncSession = Depends(get_db_session),
) -> MessageResponse:
    return await AttendanceService(db).delete_attendance_code(
        actor=current_user, code_id=code_id
    )


@router.post(
    "/attendance/submit",
    response_model=StudentAttendanceSubmitResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Submit student attendance",
    description="Public form endpoint for students to sign attendance using an active code.",
)
async def submit_attendance(
    payload: StudentAttendanceSubmitRequest,
    db: AsyncSession = Depends(get_db_session),
) -> StudentAttendanceSubmitResponse:
    return await AttendanceService(db).submit_student_attendance(payload=payload)
